variables:
  IMAGE_TAG: bankexlabs/$CI_PROJECT_NAME:$CI_JOB_NAME

stages:
  - build-node
  - release

build-node:
  image: node
  stage: build-node
  before_script:
    - npm install
  cache:
    paths:
      - node_modules/
  script:
    - npm run build
  artifacts:
    paths:
      - abi
      - build
      - config
      - public
      - server

release:
  image: docker:latest
  stage: release
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
  script:
    - docker build -f docker/Dockerfile -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}