FROM node:latest
MAINTAINER Oleg Makarov <om@bankexfoundation.org>

ADD /abi /abi
ADD /build /build
ADD /config /config
ADD /public /public
ADD /server /server
ADD /package.json /package.json

EXPOSE 80
