version: '3'

volumes:
    mongodb_data:
    contracts:

services:
  oc_donators_cab:
    image: ${IMAGE}
    container_name: oc_donators_cab
    restart: always
    volumes:
      - contracts:/opt/abi
    expose:
      - "80"
    environment:
      NODE_ENV: $NODE_ENV
      NODE_PATH: $NODE_PATH
    command: npm run staging
    depends_on:
      - donators_mongodb

  donators_mongodb:
    image: aashreys/mongo-auth:latest
    container_name: donators_mongodb
    restart: always
    volumes: 
      - mongodb_data:/data
    expose:
      - "27017"
    environment:
      AUTH: "yes"
      MONGODB_ADMIN_USER: admin
      MONGODB_ADMIN_PASS: $MONGODB_ADMIN_PASS
      MONGODB_APPLICATION_DATABASE: opch-test
      MONGODB_APPLICATION_USER: opch
      MONGODB_APPLICATION_PASS: $MONGODB_STAGE_PASS

networks:
  default:
    external:
      name: frontend_default
