jwt:
  secret: 'veryBigSecret'
  exp: 604800
  temporaryTokenExp: 1200
intervals:
  dapp:
    refreshOrganization: 3600000
    checkConnection: 120000
    reconnection: 5000
    refreshSmartContracts: 3600000