env: development
address:
  internal: 'http://127.0.0.1:8080'
  external: 'http://127.0.0.1:8080'
dirs:
  main: 'C:/NodeJS/oc_donators_cab'
  public: 'C:/NodeJS/oc_donators_cab/public/'
  abi: 'C:/NodeJS/oc_donators_cab/abi/'
mongoURI: 'mongodb://user:password@ds119268.mlab.com:19268/opch-test'
metaServer: 'http://127.0.0.1:8081'
dapp:
  provider: 'http://52.166.13.111:8535'
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'