env: development
address:
  internal: 'http://127.0.0.1:8080'
  external: 'http://127.0.0.1:8080'
dirs:
  main: 'C:/NodeJS/oc_donators_cab/'
  public: 'C:/NodeJS/oc_donators_cab/public/'
  abi: 'C:/NodeJS/oc_donators_cab/abi/'
mongoURI: 'mongodb://user:password@ds123029.mlab.com:23029/oc_donators_cab'
metaServer: 'https://opencharity.staging.bankex.team'
# metaServer: 'http://127.0.0.1:8081'
dapp:
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'
  smartContacts: 'https://donatorscab.staging.bankex.team/api/dapp/smarts'
  organizations:
  - '0x47f6aa20C90B81b5b1115B989eD853e9EFA8F5B0'
  - '0xf51dbaa3264f2dc1a950378416583be7a639ce17'
  - '0x184435d6c65fd01f3ef4bb1018dc75503c3f802f'
email:
  user: 'EMAIL'
  password: 'PASS'
  host: 'EMALHOST'
  ssl: true
cors: '*'
