env: development
address:
  internal: 'http://127.0.0.1:8080'
  external: 'http://127.0.0.1:8080'
dirs:
  main: 'C:/NodeJS/oc_donators_cab/'
  public: 'C:/NodeJS/oc_donators_cab/public/'
mongoURI: 'mongodb://user:password@ds123029.mlab.com:23029/oc_donators_cab'
# metaServer: 'https://meta.staging.bankex.team'
# opencharity: 'https://opencharity.staging.bankex.team'
metaServer: 'http://127.0.0.1:8081'
opencharity: 'http://127.0.0.1:8082'
dapp:
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'
email:
  user: 'EMAIL'
  password: 'PASS'
  host: 'EMALHOST'
  ssl: true
cors: '*'
