env: development
address:
  protocol: http
  ip: 'localhost'
  port: 8080
  web: 'localhost:8080'
dirs:
  main: 'C:/NodeJS/oc_donators_cab'
  public: 'C:/NodeJS/oc_donators_cab/public/'
  abi: 'C:/NodeJS/oc_donators_cab/abi/'
mongoURI: 'mongodb://user:password@ds119268.mlab.com:19268/opch-test'
dapp:
  provider: 'http://52.166.13.111:8535'
  token: '0x7f1dc0f5f8dafd9715ea51f6c11b92929b2dbdea'