env: development
address:
  internal: 'http://127.0.0.1:8080' # set internal docker address
  external: 'http://127.0.0.1:8080' # set external address for browser enter
jwt:  # set jsonwebtoken options
  secret: 'secret'
  exp: 604800
  temporaryTokenExp: 1200
mongoURI: 'mongodb://USER:PASSWORD@DB' # set your mongo
metaServer: 'http://127.0.0.1:8081' # set address OpenCharity Metastorage & Search machine
openCharity: 'http://127.0.0.1:8082' # set address OpenCharityDappBack API Server
dapp:
  ws: 'wss://wsprovider.staging.bankex.team:8636' # set DApp websocket provide
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e' # set token smart-contract address
email: # set email host options
  user: 'YOUR@EMAIL.COM'
  password: 'PASSWORD'
  host: 'SMPT HOST ADDRESS'
  ssl: true
cors: '*'