env: production
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://donatorscab.bankex.team'
dirs:
  main: '/oc_donators_cab/'
  public: '/oc_donators_cab/public/'
  abi: '/oc_donators_cab/abi/'
mongoURI: 'mongodb://opch:testpass@donators_mongodb:27017/opch-test'
metaServer: 'https://opencharity.bankex.team'
dapp:
  ws: 'wss://wsprovider.opencharity.bankex.team:8636'
  token: '0xa4580bdd864022a3874c57d35bf73d7717c40a48'
email:
  user: 'EMAIL'
  password: 'PASS'
  host: 'EMAILHOST'
  ssl: true
