env: production
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://donatorscab.bankex.team'
dirs:
  main: '/oc_donators_cab/'
  public: '/oc_donators_cab/public/'
mongoURI: 'mongodb://opch:testpass@donators_mongodb:27017/opch-test'
metaServer: 'https://meta.bankex.team'
opencharity: 'https://opencharity.bankex.team'
dapp:
  ws: 'wss://wsprovider.opencharity.bankex.team:8636'
  token: '0x7487a0251a0701a89cade302679b1d01c3d8a44f'
email:
  user: 'EMAIL'
  password: 'PASS'
  host: 'EMAILHOST'
  ssl: true
cors:
  - 'https://donatorscab.bankex.team'
  - 'https://opencharity.bankex.team'
  - 'https://meta.bankex.team'
