env: staging
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://donatorscab.staging.bankex.team'
dirs:
  main: '/oc_donators_cab/'
  public: '/oc_donators_cab/public/'
  abi: '/oc_donators_cab/abi/'
mongoURI: 'mongodb://opch:testpass@donators_mongodb:27017/opch-test'
metaServer: 'https://meta.staging.bankex.team'
dapp:
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'
  organizations:
  - '0x47f6aa20C90B81b5b1115B989eD853e9EFA8F5B0'
  - '0xf51dbaa3264f2dc1a950378416583be7a639ce17'
  - '0x184435d6c65fd01f3ef4bb1018dc75503c3f802f'
email:
  user: 'EMAIL'
  password: 'PASS'
  host: 'EMAILHOST'
  ssl: true
cors:
  - 'https://donatorscab.staging.bankex.team'
  - 'https://opencharity.staging.bankex.team'
  - 'https://meta.staging.bankex.team'
  - 'http://127.0.0.1:8080'
  - 'http://127.0.0.1:8081'
  - 'http://127.0.0.1:8082'
