env: staging
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://donatorscab.staging.bankex.team'
jwt:
  secret: JWTSECRETSTAGE
  exp: 604800
  temporaryTokenExp: 1200
mongoURI: 'mongodb://opch:testpass@donators_mongodb:27017/opch-test'
metaServer: 'https://meta.staging.bankex.team'
openCharity: 'https://opencharity.staging.bankex.team'
dapp:
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'
email:
  user: EMAILSTAGE
  password: EMAILPASSSTAGE
  host: EMAILHOSTSTAGE
  ssl: true
cors:
  - 'https://donatorscab.staging.bankex.team'
  - 'https://opencharity.staging.bankex.team'
  - 'https://meta.staging.bankex.team'
  - 'http://127.0.0.1:8080'
  - 'http://127.0.0.1:8081'
  - 'http://127.0.0.1:8082'
  - 'http://127.0.0.1:3000'
