env: staging
address:
  protocol: http
  ip: '0.0.0.0'
  port: 80
dirs:
  main: '/'
  public: '/public/'
  abi: '/abi/'
mongoURI: 'mongodb://opch:yo123@mongodb:27017/opch-test'
dapp:
  provider: 'http://52.166.13.111:8535'
  token: '0x9Dee536694e1f0Adc640972E61826732666345b3'
