env: staging
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://donatorscab.staging.bankex.team'
dirs:
  main: '/oc_donators_cab/'
  public: '/oc_donators_cab/public/'
  abi: '/oc_donators_cab/abi/'
mongoURI: 'mongodb://opch:testpass@donators_mongodb:27017/opch-test'
metaServer: 'https://meta.staging.bankex.team'
dapp:
  provider: 'http://52.166.13.111:8535'
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'
